// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Do3R4vXj72_Z88Gd0kL4FmskweSKQjE',
    appId: '1:78336302182:web:314409760ea5476f6be1a7',
    messagingSenderId: '78336302182',
    projectId: 'homefindr-a3c0b',
    authDomain: 'homefindr-a3c0b.firebaseapp.com',
    storageBucket: 'homefindr-a3c0b.firebasestorage.app',
    measurementId: 'G-S63PS5QQJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf6iFT3sSAHiwwMsQrxKkOB1251KYwIz0',
    appId: '1:78336302182:android:45026dfd8f54bac06be1a7',
    messagingSenderId: '78336302182',
    projectId: 'homefindr-a3c0b',
    storageBucket: 'homefindr-a3c0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgepPPn_6B-V0MnoRNkDy1Way-ENDTn4',
    appId: '1:78336302182:ios:8758bb6bdf78b5726be1a7',
    messagingSenderId: '78336302182',
    projectId: 'homefindr-a3c0b',
    storageBucket: 'homefindr-a3c0b.firebasestorage.app',
    iosBundleId: 'com.example.homefindr',
  );
}
